# Generated by Django 5.2.7 on 2026-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_postscript',
        ),
        migrations.AddField(
            model_name='service',
            name='assembly_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(choices=[('day', 'сутки'), ('piece', 'шт')], default='day', max_length=16),
        ),
        migrations.AddField(
            model_name='service',
            name='price_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
