# Generated by Django 5.2.7 on 2026-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_price_remove_service_price_postscript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='half_price_next_days',
            field=models.BooleanField(default=False),
        ),
    ]
