# Generated by Django 5.2.12 on 2026-04-03 14:21

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location', models.TextField()),
                ('tent_3x6_qty', models.PositiveIntegerField(default=0)),
                ('tent_3x3_qty', models.PositiveIntegerField(default=0)),
                ('furniture_qty', models.PositiveIntegerField(default=0)),
                ('chairs_qty', models.PositiveIntegerField(default=0)),
                ('bulb_qty', models.PositiveIntegerField(default=0)),
                ('delivery', models.BooleanField(default=False)),
                ('assembly', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('site', 'Сайт'), ('avito', 'Авито'), ('manual', 'Вручную')], default='site', max_length=32)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('inwork', 'В работе'), ('closed', 'Закрыт')], default='new', max_length=16)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
