# Generated by Django 5.2.7 on 2026-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('site', 'Сайт'), ('manual', 'Вручную')], default='site', max_length=32),
        ),
    ]
