# Generated by Django 5.2.7 on 2026-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_avito_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
