# Generated by Django 5.2.7 on 2026-04-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_rental_days'),
        ('services', '0003_service_half_price_next_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('price_unit', models.CharField(default='day', max_length=16)),
                ('assembly_price', models.PositiveIntegerField(default=0)),
                ('half_price_next_days', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applications.application')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
