# Generated by Django 5.2.12 on 2026-04-12 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона (7–20 цифр, допустимы +, пробел, дефис, скобки)', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')]),
        ),
    ]
